# Generated by Django 5.1.1 on 2024-09-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_attendance_status_attendance_is_present'),
        ('teachers', '0002_attendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
