# Generated by Django 5.1.1 on 2024-10-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
    ]
