# Generated by Django 5.1.1 on 2024-10-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_attendance_present_classes_attendance_total_classes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_present',
        ),
    ]
