# Generated by Django 5.1.1 on 2024-10-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_attendance_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectattendance',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
